# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastsql',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/fastsql',
                'lib_path': 'fastsql'},
  'syms': {'fastsql.core': {'fastsql.core.foo': ('core.html#foo', 'fastsql/core.py')}}}
